In [ ]:
import pandas as pd
import numpy as np

In [21]:
# Sample dataset with inconsistent date formats
df = pd.DataFrame({
    'Date': ['2026-01-01', '02/01/2026', 'Jan 1, 2026', '2026.01.01', '2026-01-01T00:00:00']
})
df['Date'] = pd.to_datetime(df['Date'],format='mixed', errors='coerce').dt.strftime('%d-%b-%y')
df

        Date
0  01-Jan-26
1  01-Feb-26
2  01-Jan-26
3  01-Jan-26
4  01-Jan-26

In [7]:
df = pd.DataFrame(
    {
        'Id': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
        'Name': ['JoHn', 'Jane', 'Bob', 'Alice', 'John', 'Jane', 'Bob', 'Alice', 'John', 'Jane'],
        'Age': [25, 30, 35, 40, 25, 30, 35, 40, 25, 30]
    }
)
df = df.drop_duplicates(subset=['Name'])
df

   Id   Name  Age
0   1   JoHn   25
1   2   Jane   30
2   3    Bob   35
3   4  Alice   40
4   5   John   25

In [ ]:
# Correcting Inconsistent Formats
df['Name'] = df['Name'].str.capitalize()
df = df.drop_duplicates(subset=['Name'])
df

   Id   Name  Age
0   1   John   25
1   2   Jane   30
2   3    Bob   35
3   4  Alice   40